name: Build Pip package

on:
  workflow_dispatch:
  push:


jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          architecture: x64

      - uses: pdm-project/setup-pdm@v3

      - name: Install dependencies
        run: pdm install --fail-fast --no-lock --group :all --no-self

      - name: Build package
        run: |
          rm ./dist/archivebox-*.whl
          pdm build

      - name: Install from build
        run: pip install ./dist/archivebox-*.whl

      - name: Add some links to test
        run: |
          mkdir data && cd data
          archivebox init
          archivebox add 'https://example.com'
          archivebox version
          archivebox status

      - name: Publish package distributions to PyPI
        run: pdm publish --no-build

      # - name: Push build to PyPI
      #   run: |
      #     cd pip_dist/
      #     python3 -m twine upload --repository testpypi pip_dist/*.{whl,tar.gz}
      #     python3 -m twine upload --repository pypi pip_dist/*.{whl,tar.gz}

      # - name: Commit built package
      #   run: |
      #     cd pip_dist/
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git commit -m "Pip package autobuild" -a
      
      # - name: Push build to Github
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     repository: ArchiveBox/pip-archivebox
      #     branch: ${{ github.ref }}
      #     directory: pip_dist

